from django.contrib import admin
from .models import Business, Service, Product, OpeningHour, Cart, Message, State, Variation, ProductVariation, CartItemVariation, Order, OrderItem, ProductCategory, ServiceCategory, ServiceReview, Quote, EventCategory, Award, ServiceVariation, ServiceVariationOption, Venue, VenueOpeningHour, Amenity, VenueReview, VenueView, VenueInquiry, OrderApproval, OrderTermsSignature

admin.site.register(Business)
admin.site.register(Service)
admin.site.register(Product)
admin.site.register(OpeningHour)
admin.site.register(Cart)
admin.site.register(Message)
admin.site.register(State)
admin.site.register(Variation)
admin.site.register(ProductVariation)
admin.site.register(CartItemVariation)
admin.site.register(Order)
admin.site.register(OrderItem)
admin.site.register(ProductCategory)
admin.site.register(ServiceCategory)
admin.site.register(ServiceReview)
admin.site.register(Quote)
admin.site.register(EventCategory)
admin.site.register(Award)
admin.site.register(ServiceVariation)
admin.site.register(ServiceVariationOption)
admin.site.register(Venue)
admin.site.register(VenueOpeningHour)
admin.site.register(Amenity)
admin.site.register(VenueReview)
admin.site.register(VenueView)
admin.site.register(VenueInquiry)
admin.site.register(OrderApproval)
admin.site.register(OrderTermsSignature)