# Generated by Django 4.2.13 on 2024-07-07 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_productvariation_price_service_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
