# Generated by Django 4.2.13 on 2024-07-07 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_productvariation_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together=set(),
        ),
    ]
