# Generated by Django 4.2.13 on 2024-07-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_orderitem_service_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_best_seller',
            field=models.BooleanField(default=False),
        ),
    ]
