# Generated by Django 4.2.13 on 2024-07-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_service_is_best_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='for_hire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='hire_duration',
            field=models.CharField(blank=True, choices=[('hour', 'Per Hour'), ('day', 'Per Day'), ('week', 'Per Week')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='hire_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
