# Generated by Django 4.2.13 on 2024-07-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_product_for_hire_product_hire_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='max_delivery_time',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_delivery_time',
        ),
        migrations.AddField(
            model_name='product',
            name='can_deliver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='for_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
