# Generated by Django 4.2.13 on 2024-07-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_remove_product_max_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='price_varies',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='variation',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
