# Generated by Django 4.2.13 on 2024-07-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_variation_price_varies_alter_variation_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='event_categories',
            field=models.ManyToManyField(related_name='businesses', to='event.eventcategory'),
        ),
    ]
