# Generated by Django 4.2.13 on 2024-07-16 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_eventcategory_business_event_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_radius',
            field=models.IntegerField(blank=True, help_text='Enter the delivery radius in kilometers.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='product',
            name='main_colour_theme',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black'), ('white', 'White')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_level',
            field=models.IntegerField(help_text='Enter the number of products in stock.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
