# Generated by Django 4.2.13 on 2024-07-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_alter_business_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='website',
        ),
        migrations.AddField(
            model_name='business',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
