# Generated by Django 4.2.13 on 2024-07-20 06:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_remove_business_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='delivery_radius',
            field=models.IntegerField(blank=True, help_text='Enter the delivery radius in kilometers.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='business',
            name='terms_and_conditions_pdf',
            field=models.FileField(blank=True, null=True, upload_to='terms_and_conditions/'),
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='awards/')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='event.business')),
            ],
        ),
    ]
