# Generated by Django 4.2.13 on 2024-07-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_product_setup_packdown_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='price_varies',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='price_varies',
            field=models.BooleanField(default=False),
        ),
    ]
