# Generated by Django 4.2.13 on 2024-07-20 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0025_remove_variation_price_varies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='image',
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='value',
            field=models.CharField(default='red', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='variation',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='event.variation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variation',
            name='name',
            field=models.CharField(default='size', max_length=100),
            preserve_default=False,
        ),
    ]
