# Generated by Django 4.2.13 on 2024-07-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0027_servicevariation_remove_service_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='hire_duration',
            field=models.CharField(blank=True, choices=[('hour', 'Hour'), ('day', 'Day'), ('week', 'Week')], max_length=10, null=True),
        ),
    ]
