# Generated by Django 4.2.13 on 2024-07-22 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0028_alter_service_hire_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('venue_email', models.EmailField(max_length=254)),
                ('venue_contact_number', models.CharField(max_length=20)),
                ('venue_name', models.CharField(max_length=100)),
                ('venue_address', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price_per_event', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='venue_profiles/')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='venue_covers/')),
                ('venue_image', models.ImageField(upload_to='venue_images/')),
                ('opening_hours', models.JSONField(default=dict)),
                ('event_category', models.ManyToManyField(to='event.eventcategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venue', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VenueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='venues/')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='event.venue')),
            ],
        ),
    ]
