# Generated by Django 4.2.13 on 2024-07-22 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0030_venueopeninghour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueopeninghour',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_opening_hours', to='event.venue'),
        ),
    ]
