# Generated by Django 4.2.13 on 2024-07-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0031_alter_venueopeninghour_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='venue_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
