# Generated by Django 4.2.13 on 2024-07-22 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0032_venue_venue_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='opening_hours',
        ),
    ]
