# Generated by Django 4.2.13 on 2024-07-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0033_remove_venue_opening_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='amenity_images/')),
            ],
        ),
        migrations.AddField(
            model_name='venue',
            name='ceremony_indoors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='ceremony_outdoors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='high_price_per_head',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='in_house_catering',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='low_price_per_head',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='max_reception_guests',
            field=models.IntegerField(default=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='min_reception_guests',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='amenities',
            field=models.ManyToManyField(to='event.amenity'),
        ),
    ]
