# Generated by Django 4.2.13 on 2024-07-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0035_venue_video_url_venuereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='states',
            field=models.ManyToManyField(to='event.state'),
        ),
    ]
