# Generated by Django 4.2.13 on 2024-07-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0040_alter_venue_high_price_per_head_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='high_price_per_head',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venue',
            name='low_price_per_head',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venue',
            name='price_per_event',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
