# Generated by Django 4.2.13 on 2024-07-29 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0041_alter_venue_high_price_per_head_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='price',
            new_name='total_price',
        ),
    ]
