# Generated by Django 4.2.13 on 2024-07-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0042_rename_price_cart_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='total_price',
            new_name='price',
        ),
    ]
