# Generated by Django 4.2.13 on 2024-07-30 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0043_rename_total_price_cart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitemvariation',
            name='service_variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.servicevariationoption'),
        ),
    ]
