# Generated by Django 4.2.13 on 2024-07-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0045_alter_cartitemvariation_product_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quick_hire',
            field=models.BooleanField(default=False),
        ),
    ]
