# Generated by Django 4.2.13 on 2024-08-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0048_order_status_orderapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliver_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='setup_packdown_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
