# Generated by Django 4.2.13 on 2024-08-03 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0049_order_deliver_fee_order_setup_packdown_fee_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deliver_fee',
            new_name='delivery_fee',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='setup_packdown_fee_amount',
            new_name='setup_packdown_fee',
        ),
    ]
