# Generated by Django 4.2.13 on 2024-08-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0050_rename_deliver_fee_order_delivery_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
