# Generated by Django 4.2.13 on 2024-08-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0051_alter_order_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='hire_duration',
            field=models.CharField(blank=True, choices=[('hour', 'Hour'), ('day', 'Day'), ('week', 'Week')], max_length=10, null=True),
        ),
    ]
