# Generated by Django 4.2.13 on 2024-08-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0052_orderitem_hire_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], default='delivery', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='event_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('ordered', 'ordered'), ('delivered', 'delivered')], default='ordered', max_length=20),
        ),
    ]
