# Generated by Django 4.2.13 on 2024-08-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0054_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='hire',
            field=models.BooleanField(default=False),
        ),
    ]
