# Generated by Django 4.2.13 on 2024-08-09 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0058_businesstermssignature'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTermsSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.ImageField(upload_to='order_signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.business')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='event.order')),
            ],
        ),
        migrations.DeleteModel(
            name='BusinessTermsSignature',
        ),
    ]
