# Generated by Django 4.2.13 on 2024-08-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0059_ordertermssignature_delete_businesstermssignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_intent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
