# Generated by Django 4.2.13 on 2024-08-18 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0061_venue_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='stripe_account_id',
            new_name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='subscription_start_date',
        ),
    ]
