# Generated by Django 4.2.13 on 2024-08-21 00:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0062_rename_stripe_account_id_venue_stripe_subscription_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='price_per_way',
            new_name='delivery_price_per_way',
        ),
        migrations.RemoveField(
            model_name='business',
            name='delivery_radius',
        ),
        migrations.AddField(
            model_name='business',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('price_per_way', 'Price Per Way'), ('by_radius', 'By Radius')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='max_delivery_distance',
            field=models.IntegerField(blank=True, help_text='Enter the maximum delivery distance in kilometers for Price Per Way.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='DeliveryByRadius',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius', models.IntegerField(help_text='Enter the delivery radius in kilometers.', validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.IntegerField(help_text='Enter the delivery fee for this radius.', validators=[django.core.validators.MinValueValidator(0)])),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_by_radius', to='event.business')),
            ],
        ),
    ]
