# Generated by Django 4.2.13 on 2024-08-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0063_rename_price_per_way_business_delivery_price_per_way_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='for_hire',
            new_name='for_purchase',
        ),
        migrations.RemoveField(
            model_name='product',
            name='delivery_radius',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hire_duration',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hire_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
    ]
