# Generated by Django 4.2.13 on 2024-08-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0064_rename_for_hire_product_for_purchase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='hire_duration',
        ),
    ]
