# Generated by Django 4.2.13 on 2024-08-23 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0065_remove_service_hire_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverybyradius',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_radius_options', to='event.business'),
        ),
        migrations.AlterField(
            model_name='deliverybyradius',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Enter the delivery fee for this radius.', max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='deliverybyradius',
            unique_together={('business', 'radius')},
        ),
    ]
