# Generated by Django 4.2.13 on 2024-08-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0066_alter_deliverybyradius_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='customer_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='customer_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
