# Generated by Django 4.2.13 on 2024-08-23 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0067_cart_customer_lat_cart_customer_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='hire_duration',
        ),
    ]
