# Generated by Django 4.2.13 on 2024-08-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0069_order_billing_address_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='afterpay_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
