# Generated by Django 4.2.13 on 2024-08-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0071_order_business_delivery_fees_orderitem_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partially_approved', 'Partially Approved'), ('approved', 'Approved'), ('partially_rejected', 'Partially Rejected'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
