# Generated by Django 4.2.13 on 2024-09-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0073_blogpost_paragraph_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_banner_image',
            field=models.ImageField(default='default.jpg', upload_to='blog_banner_images/'),
            preserve_default=False,
        ),
    ]
