# Generated by Django 4.2.13 on 2024-09-02 23:05

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0074_blogpost_blog_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
    ]
