# Generated by Django 4.2.13 on 2024-09-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0075_alter_paragraph_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_preview',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
