# Generated by Django 4.2.13 on 2024-09-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0076_blogpost_blog_preview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='new_releases',
            new_name='new_arrivals',
        ),
        migrations.AddField(
            model_name='service',
            name='new_arrivals',
            field=models.BooleanField(default=False),
        ),
    ]
